export const projectData = {
  projects: [
    {
      Project_ID: 1,
      Name: 'Project A',
      Created_by: 1,
    },
    {
      Project_ID: 2,
      Name: 'Project B',
      Created_by: 1,
    },
    {
      Project_ID: 5,
      Name: 'Project E',
      Created_by: 1,
    },
    {
      Project_ID: 6,
      Name: 'Project F',
      Created_by: 1,
    },
    {
      Project_ID: 899,
      Name: 'Project CD',
      Created_by: 2,
    },
    {
      Project_ID: 901,
      Name: 'Project Deez',
      Created_by: 2,
    },
  ],
  chapters: [
    {
      Chapter_ID: 1,
      Project_ID: 1,
      Chapter_Number: 1,
      Chapter_Name: 'The Beginning',
      Chapter_Content: [
        {
          Scene_ID: 1,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'CENTRAL PARK - BENCH',
          time: 'DAY',
        },
        {
          Scene_ID: 2,
          type: 'action',
          content: 'John runs across the park, dodging people as he goes.',
        },
        {
          Scene_ID: 3,
          type: 'dialogue',
          character: 'JOHN',
          extension: 'V.O.',
          parenthetical: '(whispering)',
          dialogue: "I must find the package before it's too late.",
        },
        {
          Scene_ID: 4,
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          Scene_ID: 5,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'CITY STREET - NIGHT',
          time: 'NIGHT',
        },
        {
          Scene_ID: 6,
          type: 'action',
          content:
            'A car screeches to a halt in front of the building. The driver leans out, scanning the street.',
        },
        {
          Scene_ID: 7,
          type: 'dialogue',
          character: 'SARA',
          extension: 'O.S.',
          parenthetical: '(shouting)',
          dialogue: 'Get in, now!',
        },
        {
          Scene_ID: 8,
          type: 'transition',
          transition: 'FADE OUT:',
        },
        {
          Scene_ID: 9,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'ABANDONED WAREHOUSE',
          time: 'NIGHT',
        },
        {
          Scene_ID: 10,
          type: 'action',
          content:
            'The dimly lit warehouse is filled with old, rusted machinery. A single light bulb swings from the ceiling, casting eerie shadows.',
        },
        {
          Scene_ID: 11,
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(determined)',
          dialogue: 'We have to be quiet. They could be anywhere.',
        },
        {
          Scene_ID: 12,
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(nervous)',
          dialogue: "I don't like this, John. We should have brought backup.",
        },
        {
          Scene_ID: 13,
          type: 'action',
          content:
            'Suddenly, a loud crash echoes through the building. John and Sara freeze.',
        },
        {
          Scene_ID: 14,
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(whispering)',
          dialogue: 'Stay close to me.',
        },
        {
          Scene_ID: 15,
          type: 'transition',
          transition: 'SMASH CUT TO:',
        },
        {
          Scene_ID: 16,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'ROOFTOP - NIGHT',
          time: 'NIGHT',
        },
        {
          Scene_ID: 17,
          type: 'action',
          content:
            'The city skyline glows in the distance. John and Sara emerge from a stairwell, breathless.',
        },
        {
          Scene_ID: 18,
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(relieved)',
          dialogue: 'We made it. What now?',
        },
        {
          Scene_ID: 19,
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(resolute)',
          dialogue: 'Now we wait for the signal.',
        },
        {
          Scene_ID: 20,
          type: 'action',
          content:
            'In the distance, a red flare shoots up into the sky. John nods.',
        },
        {
          Scene_ID: 21,
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(focused)',
          dialogue: "There it is. Let's move.",
        },
        {
          Scene_ID: 22,
          type: 'transition',
          transition: 'DISSOLVE TO:',
        },
        {
          Scene_ID: 23,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'SECRET LAB - NIGHT',
          time: 'NIGHT',
        },
        {
          Scene_ID: 24,
          type: 'action',
          content:
            'The lab is filled with high-tech equipment. John and Sara move stealthily, avoiding the security cameras.',
        },
        {
          Scene_ID: 25,
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(whispering)',
          dialogue: 'This place gives me the creeps.',
        },
        {
          Scene_ID: 26,
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(serious)',
          dialogue: "Stay focused. We're almost there.",
        },
        {
          Scene_ID: 27,
          type: 'action',
          content:
            "They reach a door marked 'AUTHORIZED PERSONNEL ONLY.' John pulls out a device and starts hacking the lock.",
        },
        {
          Scene_ID: 28,
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(anxious)',
          dialogue: "Hurry up, John. We don't have much time.",
        },
        {
          Scene_ID: 29,
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          Scene_ID: 30,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'CONTROL ROOM - NIGHT',
          time: 'NIGHT',
        },
        {
          Scene_ID: 31,
          type: 'action',
          content:
            'The control room is filled with monitors showing various parts of the facility. John and Sara enter and quickly start downloading data from a terminal.',
        },
        {
          Scene_ID: 32,
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(focused)',
          dialogue: "Keep an eye on the door. I'm almost done here.",
        },
        {
          Scene_ID: 33,
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(tense)',
          dialogue: "I don't like this. We need to get out of here.",
        },
        {
          Scene_ID: 34,
          type: 'action',
          content:
            'A loud alarm suddenly blares. Red lights flash as the room goes into lockdown.',
        },
        {
          Scene_ID: 35,
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(urgent)',
          dialogue: "Got it! Let's go!",
        },
        {
          Scene_ID: 36,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 2,
      Project_ID: 1,
      Chapter_Number: 2,
      Chapter_Name: 'A New Challenge',
      Chapter_Content: [
        {
          Scene_ID: 1,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'MAGICAL FOREST - CLEARING',
          time: 'DAY',
        },
        {
          Scene_ID: 2,
          type: 'action',
          content:
            'Lily steps into the clearing, her eyes scanning the surroundings for any sign of danger.',
        },
        {
          Scene_ID: 3,
          type: 'dialogue',
          character: 'LILY',
          extension: '',
          parenthetical: '(whispering to herself)',
          dialogue: "I hope I'm not too late to save the village.",
        },
        {
          Scene_ID: 4,
          type: 'action',
          content:
            'A rustling in the bushes catches her attention. She grips her staff tightly, ready for anything.',
        },
        {
          Scene_ID: 5,
          type: 'dialogue',
          character: 'MAGICAL CREATURE',
          extension: '',
          parenthetical: '(softly)',
          dialogue: 'Are you lost, traveler?',
        },
        {
          Scene_ID: 6,
          type: 'dialogue',
          character: 'LILY',
          extension: '',
          parenthetical: '(startled)',
          dialogue: 'Who... who are you?',
        },
        {
          Scene_ID: 7,
          type: 'action',
          content:
            'A small, magical creature emerges from the bushes, its eyes sparkling with curiosity.',
        },
        {
          Scene_ID: 8,
          type: 'dialogue',
          character: 'MAGICAL CREATURE',
          extension: '',
          parenthetical: '',
          dialogue:
            'I am the guardian of this forest. And you seem to be in need of guidance.',
        },
        {
          Scene_ID: 9,
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          Scene_ID: 10,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'VILLAGE - SQUARE',
          time: 'DAY',
        },
        {
          Scene_ID: 11,
          type: 'action',
          content:
            'Villagers gather around, murmuring nervously. Lily approaches the elder, a look of determination on her face.',
        },
        {
          Scene_ID: 12,
          type: 'dialogue',
          character: 'LILY',
          extension: '',
          parenthetical: '',
          dialogue: 'Elder, I need your help. The forest is in danger.',
        },
        {
          Scene_ID: 13,
          type: 'dialogue',
          character: 'ELDER',
          extension: '',
          parenthetical: '(gravely)',
          dialogue: 'We have sensed it too, child. What must we do?',
        },
        {
          Scene_ID: 14,
          type: 'action',
          content:
            'Lily pulls out an ancient map, pointing to a marked location. The villagers gather closer, eager to hear her plan.',
        },
        {
          Scene_ID: 15,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 3,
      Project_ID: 1,
      Chapter_Number: 3,
      Chapter_Name: 'Secrets Unveiled',
      Chapter_Content: [
        {
          Scene_ID: 1,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'DESERT - DUNE',
          time: 'DAY',
        },
        {
          Scene_ID: 2,
          type: 'action',
          content:
            'A solitary figure trudges up the dune, the sun blazing overhead.',
        },
        {
          Scene_ID: 3,
          type: 'dialogue',
          character: 'TRAVELER',
          extension: 'V.O.',
          parenthetical: '',
          dialogue: "I've been walking for days. Where is the oasis?",
        },
        {
          Scene_ID: 4,
          type: 'action',
          content:
            'The traveler reaches the top and looks out over the endless sea of sand, despair creeping into their eyes.',
        },
        {
          Scene_ID: 5,
          type: 'dialogue',
          character: 'TRAVELER',
          extension: '',
          parenthetical: '(desperate)',
          dialogue: 'There has to be water somewhere...',
        },
        {
          Scene_ID: 6,
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          Scene_ID: 7,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'HIDDEN CAVE - ENTRANCE',
          time: 'DAY',
        },
        {
          Scene_ID: 8,
          type: 'action',
          content:
            'The traveler stumbles upon a hidden cave entrance, partially concealed by rocks.',
        },
        {
          Scene_ID: 9,
          type: 'dialogue',
          character: 'TRAVELER',
          extension: '',
          parenthetical: '(hopeful)',
          dialogue: "This might be it. I have to see what's inside.",
        },
        {
          Scene_ID: 10,
          type: 'action',
          content:
            'With renewed energy, the traveler squeezes through the narrow opening and into the darkness.',
        },
        {
          Scene_ID: 11,
          type: 'transition',
          transition: 'FADE IN:',
        },
        {
          Scene_ID: 12,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'HIDDEN CAVE - INNER CHAMBER',
          time: 'DAY',
        },
        {
          Scene_ID: 13,
          type: 'action',
          content:
            'The traveler enters a vast inner chamber, illuminated by an ethereal glow from a mysterious pool of water.',
        },
        {
          Scene_ID: 14,
          type: 'dialogue',
          character: 'TRAVELER',
          extension: '',
          parenthetical: '(awed)',
          dialogue: 'This... this is incredible.',
        },
        {
          Scene_ID: 15,
          type: 'action',
          content:
            'The traveler kneels by the pool and takes a sip. The water is cool and refreshing, rejuvenating their spirit.',
        },
        {
          Scene_ID: 16,
          type: 'dialogue',
          character: 'TRAVELER',
          extension: '',
          parenthetical: '(grateful)',
          dialogue: "I've found it. The oasis is real.",
        },
        {
          Scene_ID: 17,
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          Scene_ID: 18,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'DESERT - NIGHT',
          time: 'NIGHT',
        },
        {
          Scene_ID: 19,
          type: 'action',
          content:
            'The traveler sets up camp near the cave entrance, the stars shining brightly overhead.',
        },
        {
          Scene_ID: 20,
          type: 'dialogue',
          character: 'TRAVELER',
          extension: '',
          parenthetical: '(content)',
          dialogue: 'Tomorrow, I will explore more. For now, I rest.',
        },
        {
          Scene_ID: 21,
          type: 'action',
          content:
            'The traveler lies down, a smile on their face, as they drift off to sleep.',
        },
        {
          Scene_ID: 22,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 4,
      Project_ID: 1,
      Chapter_Number: 4,
      Chapter_Name: 'The Journey Begins',
      Chapter_Content: [
        {
          Scene_ID: 1,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'SUBWAY STATION',
          time: 'DAY',
        },
        {
          Scene_ID: 2,
          type: 'action',
          content:
            'Commuters rush past as the train pulls into the station. The doors open and a flood of people exit.',
        },
        {
          Scene_ID: 3,
          type: 'dialogue',
          character: 'ANNOUNCER',
          extension: 'V.O.',
          parenthetical: '',
          dialogue: 'Next stop, Central Square.',
        },
        {
          Scene_ID: 4,
          type: 'action',
          content:
            'Emma, a young woman with a determined look, pushes her way through the crowd and boards the train.',
        },
        {
          Scene_ID: 5,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(to herself)',
          dialogue: 'Just one more stop.',
        },
        {
          Scene_ID: 6,
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          Scene_ID: 7,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'CENTRAL SQUARE',
          time: 'DAY',
        },
        {
          Scene_ID: 8,
          type: 'action',
          content:
            'Emma steps out into the bustling square, scanning the area with a focused gaze.',
        },
        {
          Scene_ID: 9,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(determined)',
          dialogue: "He said he'd be here.",
        },
        {
          Scene_ID: 10,
          type: 'action',
          content:
            'She spots a man in a dark coat standing by a statue, looking around nervously.',
        },
        {
          Scene_ID: 11,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(to herself)',
          dialogue: "That's him.",
        },
        {
          Scene_ID: 12,
          type: 'transition',
          transition: 'FADE IN:',
        },
        {
          Scene_ID: 13,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'COFFEE SHOP',
          time: 'DAY',
        },
        {
          Scene_ID: 14,
          type: 'action',
          content:
            'Emma and the man sit at a corner table, speaking in hushed tones.',
        },
        {
          Scene_ID: 15,
          type: 'dialogue',
          character: 'MAN',
          extension: '',
          parenthetical: '',
          dialogue: 'Did you bring it?',
        },
        {
          Scene_ID: 16,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(nervous)',
          dialogue: "Yes, but I need to know it's safe first.",
        },
        {
          Scene_ID: 17,
          type: 'action',
          content:
            'The man slides a small package across the table. Emma opens it to reveal a USB drive.',
        },
        {
          Scene_ID: 18,
          type: 'dialogue',
          character: 'MAN',
          extension: '',
          parenthetical: '',
          dialogue: "Everything you need is on there. Now, where's the money?",
        },
        {
          Scene_ID: 19,
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          Scene_ID: 20,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'COFFEE SHOP - BACK ALLEY',
          time: 'DAY',
        },
        {
          Scene_ID: 21,
          type: 'action',
          content:
            'Emma and the man exit through the back door into a quiet alley. Emma hands him an envelope.',
        },
        {
          Scene_ID: 22,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(serious)',
          dialogue:
            "Here's your money. Now tell me, who else knows about this?",
        },
        {
          Scene_ID: 23,
          type: 'dialogue',
          character: 'MAN',
          extension: '',
          parenthetical: '(hesitant)',
          dialogue: 'No one. Just you and me.',
        },
        {
          Scene_ID: 24,
          type: 'action',
          content:
            'Emma nods, but her eyes betray her mistrust. She tucks the USB drive into her coat pocket.',
        },
        {
          Scene_ID: 25,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 5,
      Project_ID: 2,
      Chapter_Number: 1,
      Chapter_Name: 'Crossroads',
      Chapter_Content: [
        {
          Scene_ID: 1,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'BEACH',
          time: 'SUNSET',
        },
        {
          Scene_ID: 2,
          type: 'action',
          content:
            'Waves crash gently on the shore as the sky glows orange and pink.',
        },
        {
          Scene_ID: 3,
          type: 'dialogue',
          character: 'LUCAS',
          extension: '',
          parenthetical: '(thoughtful)',
          dialogue: "I never thought we'd end up here.",
        },
        {
          Scene_ID: 4,
          type: 'dialogue',
          character: 'AMY',
          extension: '',
          parenthetical: '(smiling)',
          dialogue: "It's beautiful, isn't it?",
        },
        {
          Scene_ID: 5,
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          Scene_ID: 6,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'CABIN',
          time: 'NIGHT',
        },
        {
          Scene_ID: 7,
          type: 'action',
          content:
            'A cozy cabin with a roaring fireplace. Lucas and Amy sit on the couch, looking at old photographs.',
        },
        {
          Scene_ID: 8,
          type: 'dialogue',
          character: 'LUCAS',
          extension: '',
          parenthetical: '(nostalgic)',
          dialogue: 'Remember this? Our first trip together.',
        },
        {
          Scene_ID: 9,
          type: 'dialogue',
          character: 'AMY',
          extension: '',
          parenthetical: '(laughing)',
          dialogue: 'How could I forget? We got lost for hours.',
        },
        {
          Scene_ID: 10,
          type: 'transition',
          transition: 'FADE IN:',
        },
        {
          Scene_ID: 11,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'MOUNTAIN TRAIL',
          time: 'DAY',
        },
        {
          Scene_ID: 12,
          type: 'action',
          content:
            'Lucas and Amy hike up a rugged trail, surrounded by breathtaking mountain scenery.',
        },
        {
          Scene_ID: 13,
          type: 'dialogue',
          character: 'LUCAS',
          extension: '',
          parenthetical: '(panting)',
          dialogue: "We're almost there.",
        },
        {
          Scene_ID: 14,
          type: 'dialogue',
          character: 'AMY',
          extension: '',
          parenthetical: '(encouraging)',
          dialogue: 'Just a little further!',
        },
        {
          Scene_ID: 15,
          type: 'transition',
          transition: 'SMASH CUT TO:',
        },
        {
          Scene_ID: 16,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'MOUNTAIN SUMMIT',
          time: 'DAY',
        },
        {
          Scene_ID: 17,
          type: 'action',
          content:
            'At the summit, Lucas and Amy take in the panoramic view, the world stretching out below them.',
        },
        {
          Scene_ID: 18,
          type: 'dialogue',
          character: 'LUCAS',
          extension: '',
          parenthetical: '(awed)',
          dialogue: "It's incredible.",
        },
        {
          Scene_ID: 19,
          type: 'dialogue',
          character: 'AMY',
          extension: '',
          parenthetical: '(smiling)',
          dialogue: "I knew you'd love it.",
        },
        {
          Scene_ID: 20,
          type: 'action',
          content:
            'They sit down together, enjoying the moment of triumph and tranquility.',
        },
        {
          Scene_ID: 21,
          type: 'dialogue',
          character: 'LUCAS',
          extension: '',
          parenthetical: '(reflective)',
          dialogue: "We've come so far.",
        },
        {
          Scene_ID: 22,
          type: 'dialogue',
          character: 'AMY',
          extension: '',
          parenthetical: '(content)',
          dialogue: 'And we have so much more to see.',
        },
        {
          Scene_ID: 23,
          type: 'transition',
          transition: 'DISSOLVE TO:',
        },
        {
          Scene_ID: 24,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'ART GALLERY',
          time: 'NIGHT',
        },
        {
          Scene_ID: 25,
          type: 'action',
          content:
            'Lucas and Amy walk through a modern art gallery, stopping to admire the paintings.',
        },
        {
          Scene_ID: 26,
          type: 'dialogue',
          character: 'LUCAS',
          extension: '',
          parenthetical: '(curious)',
          dialogue: 'What do you think this one means?',
        },
        {
          Scene_ID: 27,
          type: 'dialogue',
          character: 'AMY',
          extension: '',
          parenthetical: '(thoughtful)',
          dialogue: "I think it's about finding beauty in chaos.",
        },
        {
          Scene_ID: 28,
          type: 'action',
          content:
            'Lucas nods, pondering her words as they move on to the next piece.',
        },
        {
          Scene_ID: 29,
          type: 'dialogue',
          character: 'LUCAS',
          extension: '',
          parenthetical: '(smiling)',
          dialogue: "You've always had an eye for art.",
        },
        {
          Scene_ID: 30,
          type: 'dialogue',
          character: 'AMY',
          extension: '',
          parenthetical: '(smiling back)',
          dialogue: "And you've always been my biggest fan.",
        },
        {
          Scene_ID: 31,
          type: 'action',
          content:
            'They share a laugh, their bond strengthened by the shared experience.',
        },
        {
          Scene_ID: 32,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 6,
      Project_ID: 2,
      Chapter_Number: 2,
      Chapter_Name: 'Hidden Truths',
      Chapter_Content: [
        {
          Scene_ID: 1,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'FOREST CLEARING',
          time: 'DAY',
        },
        {
          Scene_ID: 2,
          type: 'action',
          content:
            'Birds chirp as sunlight filters through the trees. Emma stands in the clearing, looking around.',
        },
        {
          Scene_ID: 3,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(excited)',
          dialogue: 'I think this is the place!',
        },
        {
          Scene_ID: 4,
          type: 'dialogue',
          character: 'JACK',
          extension: '',
          parenthetical: '(skeptical)',
          dialogue:
            'Are you sure? It looks like any other part of the forest to me.',
        },
        {
          Scene_ID: 5,
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          Scene_ID: 6,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'OLD CABIN',
          time: 'DAY',
        },
        {
          Scene_ID: 7,
          type: 'action',
          content:
            'The interior is dusty and filled with cobwebs. Emma and Jack carefully step inside.',
        },
        {
          Scene_ID: 8,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(whispering)',
          dialogue: 'This place gives me the creeps.',
        },
        {
          Scene_ID: 9,
          type: 'dialogue',
          character: 'JACK',
          extension: '',
          parenthetical: '(reassuring)',
          dialogue: "Don't worry. We're just here to look around.",
        },
        {
          Scene_ID: 10,
          type: 'transition',
          transition: 'FADE IN:',
        },
        {
          Scene_ID: 11,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'LAKE',
          time: 'SUNSET',
        },
        {
          Scene_ID: 12,
          type: 'action',
          content:
            'The lake is calm, with the sun setting in the background. Emma and Jack sit on the shore, skipping stones.',
        },
        {
          Scene_ID: 13,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(thoughtful)',
          dialogue: "Do you think we'll find what we're looking for?",
        },
        {
          Scene_ID: 14,
          type: 'dialogue',
          character: 'JACK',
          extension: '',
          parenthetical: '(confident)',
          dialogue: 'I know we will. We just have to keep searching.',
        },
        {
          Scene_ID: 15,
          type: 'transition',
          transition: 'SMASH CUT TO:',
        },
        {
          Scene_ID: 16,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'CAVE',
          time: 'NIGHT',
        },
        {
          Scene_ID: 17,
          type: 'action',
          content:
            'Emma and Jack navigate the dark, narrow passages with flashlights.',
        },
        {
          Scene_ID: 18,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(nervous)',
          dialogue: "I don't like this. It's too quiet.",
        },
        {
          Scene_ID: 19,
          type: 'dialogue',
          character: 'JACK',
          extension: '',
          parenthetical: '(determined)',
          dialogue: "Stay close. We're almost there.",
        },
        {
          Scene_ID: 20,
          type: 'action',
          content:
            'They reach a large chamber where the walls are covered in ancient drawings.',
        },
        {
          Scene_ID: 21,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(awed)',
          dialogue: 'This must be it. The lost cave of legends.',
        },
        {
          Scene_ID: 22,
          type: 'dialogue',
          character: 'JACK',
          extension: '',
          parenthetical: '(excited)',
          dialogue: 'We did it, Emma. We found it!',
        },
        {
          Scene_ID: 23,
          type: 'transition',
          transition: 'DISSOLVE TO:',
        },
        {
          Scene_ID: 24,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'MUSEUM',
          time: 'DAY',
        },
        {
          Scene_ID: 25,
          type: 'action',
          content:
            'Emma and Jack stand in front of a display case showcasing artifacts from their adventure.',
        },
        {
          Scene_ID: 26,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(proud)',
          dialogue: 'We made history.',
        },
        {
          Scene_ID: 27,
          type: 'dialogue',
          character: 'JACK',
          extension: '',
          parenthetical: '(smiling)',
          dialogue: 'And the adventure is just beginning.',
        },
        {
          Scene_ID: 28,
          type: 'action',
          content:
            'They share a look, knowing there are more discoveries to be made.',
        },
        {
          Scene_ID: 29,
          type: 'dialogue',
          character: 'EMMA',
          extension: '',
          parenthetical: '(excited)',
          dialogue: "What's next?",
        },
        {
          Scene_ID: 30,
          type: 'dialogue',
          character: 'JACK',
          extension: '',
          parenthetical: '(determined)',
          dialogue: "The world is full of mysteries. Let's go find them.",
        },
        {
          Scene_ID: 31,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 7,
      Project_ID: 2,
      Chapter_Number: 3,
      Chapter_Name: 'Rising Tensions',
      Chapter_Content: [
        {
          Scene_ID: 37,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'OFFICE - NIGHT',
          time: 'NIGHT',
        },
        {
          Scene_ID: 38,
          type: 'action',
          content:
            'The office is dimly lit. Papers are scattered across the desk.',
        },
        {
          Scene_ID: 39,
          type: 'dialogue',
          character: 'MARK',
          extension: '',
          parenthetical: '(angry)',
          dialogue: "We can't keep going like this!",
        },
        {
          Scene_ID: 40,
          type: 'dialogue',
          character: 'SOPHIA',
          extension: '',
          parenthetical: '(calm)',
          dialogue: 'We need to find a solution, Mark.',
        },
        {
          Scene_ID: 41,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 8,
      Project_ID: 2,
      Chapter_Number: 4,
      Chapter_Name: 'A Twist of Fate',
      Chapter_Content: [
        {
          Scene_ID: 42,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'BEACH - DAY',
          time: 'DAY',
        },
        {
          Scene_ID: 43,
          type: 'action',
          content:
            'Waves crash on the shore. A storm is brewing in the distance.',
        },
        {
          Scene_ID: 44,
          type: 'dialogue',
          character: 'ANNA',
          extension: '',
          parenthetical: '(worried)',
          dialogue: 'We need to get back before the storm hits.',
        },
        {
          Scene_ID: 45,
          type: 'dialogue',
          character: 'TOM',
          extension: '',
          parenthetical: '(determined)',
          dialogue: 'Just a few more minutes.',
        },
        {
          Scene_ID: 46,
          type: 'transition',
          transition: 'CUT TO:',
        },
      ],
    },
    {
      Chapter_ID: 9,
      Project_ID: 5,
      Chapter_Number: 1,
      Chapter_Name: 'Battle Lines',
      Chapter_Content: [
        {
          Scene_ID: 47,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'BATTLEFIELD',
          time: 'DAY',
        },
        {
          Scene_ID: 48,
          type: 'action',
          content: 'Soldiers line up on either side. The tension is palpable.',
        },
        {
          Scene_ID: 49,
          type: 'dialogue',
          character: 'GENERAL',
          extension: '',
          parenthetical: '(commanding)',
          dialogue: 'Hold the line!',
        },
        {
          Scene_ID: 50,
          type: 'dialogue',
          character: 'SOLDIER',
          extension: '',
          parenthetical: '(anxious)',
          dialogue: "They're getting closer!",
        },
        {
          Scene_ID: 51,
          type: 'transition',
          transition: 'FADE TO BLACK:',
        },
      ],
    },
    {
      Chapter_ID: 10,
      Project_ID: 5,
      Chapter_Number: 2,
      Chapter_Name: 'Unexpected Allies',
      Chapter_Content: [
        {
          Scene_ID: 52,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'FOREST - NIGHT',
          time: 'NIGHT',
        },
        {
          Scene_ID: 53,
          type: 'action',
          content:
            'The moonlight filters through the trees. A group of figures approach cautiously.',
        },
        {
          Scene_ID: 54,
          type: 'dialogue',
          character: 'LEADER',
          extension: '',
          parenthetical: '(whispering)',
          dialogue: "We're not alone.",
        },
        {
          Scene_ID: 55,
          type: 'dialogue',
          character: 'ALLY',
          extension: '',
          parenthetical: '(calm)',
          dialogue: 'We come in peace.',
        },
        {
          Scene_ID: 56,
          type: 'transition',
          transition: 'CUT TO:',
        },
      ],
    },
    {
      Chapter_ID: 11,
      Project_ID: 5,
      Chapter_Number: 3,
      Chapter_Name: 'The Darkest Hour',
      Chapter_Content: [
        {
          Scene_ID: 57,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'BUNKER',
          time: 'NIGHT',
        },
        {
          Scene_ID: 58,
          type: 'action',
          content:
            'The bunker is filled with anxious faces. Supplies are running low.',
        },
        {
          Scene_ID: 59,
          type: 'dialogue',
          character: 'CAPTAIN',
          extension: '',
          parenthetical: '(resigned)',
          dialogue: 'This might be our last stand.',
        },
        {
          Scene_ID: 60,
          type: 'dialogue',
          character: 'LIEUTENANT',
          extension: '',
          parenthetical: '(determined)',
          dialogue: "We'll make it through this.",
        },
        {
          Scene_ID: 61,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 12,
      Project_ID: 5,
      Chapter_Number: 4,
      Chapter_Name: 'Revelation',
      Chapter_Content: [
        {
          Scene_ID: 62,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'LAB',
          time: 'DAY',
        },
        {
          Scene_ID: 63,
          type: 'action',
          content:
            'Scientists are gathered around a computer screen. A discovery is made.',
        },
        {
          Scene_ID: 64,
          type: 'dialogue',
          character: 'SCIENTIST',
          extension: '',
          parenthetical: '(excited)',
          dialogue: 'This changes everything!',
        },
        {
          Scene_ID: 65,
          type: 'dialogue',
          character: 'ASSISTANT',
          extension: '',
          parenthetical: '(shocked)',
          dialogue: 'We need to tell the others.',
        },
        {
          Scene_ID: 66,
          type: 'transition',
          transition: 'CUT TO:',
        },
      ],
    },
    {
      Chapter_ID: 13,
      Project_ID: 6,
      Chapter_Number: 1,
      Chapter_Name: 'The Turning Point',
      Chapter_Content: [
        {
          Scene_ID: 67,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'MOUNTAIN PASS',
          time: 'DAWN',
        },
        {
          Scene_ID: 68,
          type: 'action',
          content:
            'A group of travelers makes their way through the pass. The sun begins to rise.',
        },
        {
          Scene_ID: 69,
          type: 'dialogue',
          character: 'GUIDE',
          extension: '',
          parenthetical: '(determined)',
          dialogue: 'We must keep moving.',
        },
        {
          Scene_ID: 70,
          type: 'dialogue',
          character: 'TRAVELER',
          extension: '',
          parenthetical: '(exhausted)',
          dialogue: "I don't know if I can.",
        },
        {
          Scene_ID: 71,
          type: 'transition',
          transition: 'FADE TO:',
        },
      ],
    },
    {
      Chapter_ID: 14,
      Project_ID: 6,
      Chapter_Number: 2,
      Chapter_Name: 'Shadows of the Past',
      Chapter_Content: [
        {
          Scene_ID: 72,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'ANCIENT RUINS',
          time: 'DAY',
        },
        {
          Scene_ID: 73,
          type: 'action',
          content:
            'Dusty corridors with carvings on the walls. The explorers move cautiously.',
        },
        {
          Scene_ID: 74,
          type: 'dialogue',
          character: 'ARCHAEOLOGIST',
          extension: '',
          parenthetical: '(amazed)',
          dialogue: 'These markings are thousands of years old.',
        },
        {
          Scene_ID: 75,
          type: 'dialogue',
          character: 'ASSISTANT',
          extension: '',
          parenthetical: '(nervous)',
          dialogue: "I feel like we're being watched.",
        },
        {
          Scene_ID: 76,
          type: 'transition',
          transition: 'CUT TO:',
        },
      ],
    },
    {
      Chapter_ID: 15,
      Project_ID: 6,
      Chapter_Number: 3,
      Chapter_Name: 'The Great Escape',
      Chapter_Content: [
        {
          Scene_ID: 77,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'PRISON CELL',
          time: 'NIGHT',
        },
        {
          Scene_ID: 78,
          type: 'action',
          content:
            'A prisoner works to pick the lock. Footsteps echo in the corridor.',
        },
        {
          Scene_ID: 79,
          type: 'dialogue',
          character: 'PRISONER',
          extension: '',
          parenthetical: '(whispering)',
          dialogue: 'Almost there...',
        },
        {
          Scene_ID: 80,
          type: 'dialogue',
          character: 'GUARD',
          extension: '',
          parenthetical: '(suspicious)',
          dialogue: "Who's there?",
        },
        {
          Scene_ID: 81,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 16,
      Project_ID: 6,
      Chapter_Number: 4,
      Chapter_Name: 'Unlikely Heroes',
      Chapter_Content: [
        {
          Scene_ID: 82,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'VILLAGE SQUARE',
          time: 'DAY',
        },
        {
          Scene_ID: 83,
          type: 'action',
          content:
            'Villagers gather to discuss their plan. The atmosphere is tense.',
        },
        {
          Scene_ID: 84,
          type: 'dialogue',
          character: 'LEADER',
          extension: '',
          parenthetical: '(determined)',
          dialogue: 'We fight back, starting now.',
        },
        {
          Scene_ID: 85,
          type: 'dialogue',
          character: 'VILLAGER',
          extension: '',
          parenthetical: '(fearful)',
          dialogue: "But we're just farmers!",
        },
        {
          Scene_ID: 86,
          type: 'transition',
          transition: 'FADE TO BLACK:',
        },
      ],
    },
    {
      Chapter_ID: 17,
      Project_ID: 899,
      Chapter_Number: 1,
      Chapter_Name: 'Conspiracy Uncovered',
      Chapter_Content: [
        {
          Scene_ID: 87,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'SECRET BASEMENT',
          time: 'NIGHT',
        },
        {
          Scene_ID: 88,
          type: 'action',
          content:
            'Hidden documents are scattered on a table. The air is thick with tension.',
        },
        {
          Scene_ID: 89,
          type: 'dialogue',
          character: 'AGENT',
          extension: '',
          parenthetical: '(urgent)',
          dialogue: "We've got to expose this.",
        },
        {
          Scene_ID: 90,
          type: 'dialogue',
          character: 'INFORMANT',
          extension: '',
          parenthetical: '(nervous)',
          dialogue: "They'll come after us.",
        },
        {
          Scene_ID: 91,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 18,
      Project_ID: 899,
      Chapter_Number: 2,
      Chapter_Name: 'The Final Countdown',
      Chapter_Content: [
        {
          Scene_ID: 92,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'CONTROL ROOM',
          time: 'DAY',
        },
        {
          Scene_ID: 93,
          type: 'action',
          content:
            'Monitors display a ticking clock. The team works frantically.',
        },
        {
          Scene_ID: 94,
          type: 'dialogue',
          character: 'TECH',
          extension: '',
          parenthetical: '(panicking)',
          dialogue: 'We only have minutes left!',
        },
        {
          Scene_ID: 95,
          type: 'dialogue',
          character: 'LEADER',
          extension: '',
          parenthetical: '(focused)',
          dialogue: 'Stay on task. We can do this.',
        },
        {
          Scene_ID: 96,
          type: 'transition',
          transition: 'CUT TO:',
        },
      ],
    },
    {
      Chapter_ID: 19,
      Project_ID: 899,
      Chapter_Number: 3,
      Chapter_Name: 'A Glimmer of Hope',
      Chapter_Content: [
        {
          Scene_ID: 97,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'CITY STREETS',
          time: 'DAWN',
        },
        {
          Scene_ID: 98,
          type: 'action',
          content:
            'The city is in ruins. Survivors begin to emerge, looking for hope.',
        },
        {
          Scene_ID: 99,
          type: 'dialogue',
          character: 'CITIZEN',
          extension: '',
          parenthetical: '(hopeful)',
          dialogue: 'We can rebuild.',
        },
        {
          Scene_ID: 100,
          type: 'dialogue',
          character: 'LEADER',
          extension: '',
          parenthetical: '(determined)',
          dialogue: "We'll make it through this.",
        },
        {
          Scene_ID: 101,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 20,
      Project_ID: 899,
      Chapter_Number: 4,
      Chapter_Name: 'The Ultimate Sacrifice',
      Chapter_Content: [
        {
          Scene_ID: 102,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'CLIFFSIDE',
          time: 'NIGHT',
        },
        {
          Scene_ID: 103,
          type: 'action',
          content:
            'A hero stands at the edge, ready to make the ultimate sacrifice.',
        },
        {
          Scene_ID: 104,
          type: 'dialogue',
          character: 'HERO',
          extension: '',
          parenthetical: '(resigned)',
          dialogue: 'This is the only way.',
        },
        {
          Scene_ID: 105,
          type: 'dialogue',
          character: 'ALLY',
          extension: '',
          parenthetical: '(desperate)',
          dialogue: 'There has to be another way!',
        },
        {
          Scene_ID: 106,
          type: 'transition',
          transition: 'FADE TO BLACK:',
        },
      ],
    },
    {
      Chapter_ID: 21,
      Project_ID: 901,
      Chapter_Number: 1,
      Chapter_Name: 'Redemption',
      Chapter_Content: [
        {
          Scene_ID: 107,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'CHURCH',
          time: 'DAY',
        },
        {
          Scene_ID: 108,
          type: 'action',
          content:
            'Sunlight streams through stained glass windows. A figure kneels in prayer.',
        },
        {
          Scene_ID: 109,
          type: 'dialogue',
          character: 'PRIEST',
          extension: '',
          parenthetical: '(gentle)',
          dialogue: 'You are forgiven.',
        },
        {
          Scene_ID: 110,
          type: 'dialogue',
          character: 'FIGURE',
          extension: '',
          parenthetical: '(relieved)',
          dialogue: 'Thank you.',
        },
        {
          Scene_ID: 111,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 22,
      Project_ID: 901,
      Chapter_Number: 2,
      Chapter_Name: 'The Last Stand',
      Chapter_Content: [
        {
          Scene_ID: 112,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'FORTRESS',
          time: 'NIGHT',
        },
        {
          Scene_ID: 113,
          type: 'action',
          content:
            'Defenders prepare for the final assault. Torches light up the walls.',
        },
        {
          Scene_ID: 114,
          type: 'dialogue',
          character: 'COMMANDER',
          extension: '',
          parenthetical: '(determined)',
          dialogue: 'Hold the line at all costs!',
        },
        {
          Scene_ID: 115,
          type: 'dialogue',
          character: 'SOLDIER',
          extension: '',
          parenthetical: '(resolute)',
          dialogue: 'For our home!',
        },
        {
          Scene_ID: 116,
          type: 'transition',
          transition: 'CUT TO:',
        },
      ],
    },
    {
      Chapter_ID: 23,
      Project_ID: 901,
      Chapter_Number: 3,
      Chapter_Name: 'Aftermath',
      Chapter_Content: [
        {
          Scene_ID: 117,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'BATTLEFIELD',
          time: 'DAWN',
        },
        {
          Scene_ID: 118,
          type: 'action',
          content:
            'The battlefield is littered with debris. Survivors search for loved ones.',
        },
        {
          Scene_ID: 119,
          type: 'dialogue',
          character: 'SURVIVOR',
          extension: '',
          parenthetical: '(sorrowful)',
          dialogue: 'We made it.',
        },
        {
          Scene_ID: 120,
          type: 'dialogue',
          character: 'LEADER',
          extension: '',
          parenthetical: '(determined)',
          dialogue: 'We rebuild from here.',
        },
        {
          Scene_ID: 121,
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 24,
      Project_ID: 901,
      Chapter_Number: 4,
      Chapter_Name: 'New Beginnings',
      Chapter_Content: [
        {
          Scene_ID: 122,
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'VILLAGE',
          time: 'DAY',
        },
        {
          Scene_ID: 123,
          type: 'action',
          content:
            'Villagers work together to rebuild. The sun shines brightly.',
        },
        {
          Scene_ID: 124,
          type: 'dialogue',
          character: 'ELDER',
          extension: '',
          parenthetical: '(hopeful)',
          dialogue: 'A new day dawns.',
        },
        {
          Scene_ID: 125,
          type: 'dialogue',
          character: 'CHILD',
          extension: '',
          parenthetical: '(curious)',
          dialogue: 'What happens next?',
        },
        {
          Scene_ID: 126,
          type: 'transition',
          transition: 'FADE TO BLACK:',
        },
      ],
    },
  ],
  characters: [
    {
      Character_ID: 1,
      Project_ID: 1,
      Name: 'John Doe',
      Age: 30,
      Role: 'Protagonist',
      First_Chapter_Appearance: 1,
      Description: 'A brave and determined leader who fights for justice.',
      Image: '',
      Date_of_Birth: '1994-01-15',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Reading, Hiking, Strategy Games',
    },
    {
      Character_ID: 2,
      Project_ID: 2,
      Name: 'Jane Smith',
      Age: 25,
      Role: 'Antagonist',
      First_Chapter_Appearance: 5,
      Description: 'A cunning and ambitious individual with a mysterious past.',
      Image: '',
      Date_of_Birth: '1999-06-22',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Chess, Painting, Fencing',
    },
    {
      Character_ID: 3,
      Project_ID: 1,
      Name: 'Alex Johnson',
      Age: 35,
      Role: 'Supporting',
      First_Chapter_Appearance: 2,
      Description:
        'A loyal friend and skilled warrior with a troubled history.',
      Image: '',
      Date_of_Birth: '1989-11-05',
      Date_of_Death: '',
      Gender: 'Non-binary',
      Interests_Hobbies: 'Martial Arts, Cooking, Gardening',
    },
    {
      Character_ID: 4,
      Project_ID: 1,
      Name: 'Emily Davis',
      Age: 28,
      Role: 'Supporting',
      First_Chapter_Appearance: 3,
      Description: 'A brilliant scientist with a passion for discovery.',
      Image: '',
      Date_of_Birth: '1996-03-18',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Reading, Experimenting, Traveling',
    },
    {
      Character_ID: 5,
      Project_ID: 2,
      Name: 'Michael Brown',
      Age: 40,
      Role: 'Protagonist',
      First_Chapter_Appearance: 5,
      Description:
        'A seasoned detective with a sharp mind and a strong sense of justice.',
      Image: '',
      Date_of_Birth: '1984-07-11',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Puzzle Solving, Jogging, Fishing',
    },
    {
      Character_ID: 6,
      Project_ID: 5,
      Name: 'Samantha White',
      Age: 32,
      Role: 'Protagonist',
      First_Chapter_Appearance: 9,
      Description:
        'A fearless explorer with a knack for uncovering hidden secrets.',
      Image: '',
      Date_of_Birth: '1992-12-25',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Rock Climbing, Photography, Archaeology',
    },
    {
      Character_ID: 7,
      Project_ID: 6,
      Name: 'Robert Green',
      Age: 45,
      Role: 'Supporting',
      First_Chapter_Appearance: 13,
      Description: 'A wise mentor with years of experience and knowledge.',
      Image: '',
      Date_of_Birth: '1979-09-03',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Meditation, Teaching, Chess',
    },
    {
      Character_ID: 8,
      Project_ID: 899,
      Name: 'Laura Black',
      Age: 29,
      Role: 'Antagonist',
      First_Chapter_Appearance: 17,
      Description: 'A charismatic leader with a dark side and a hidden agenda.',
      Image: '',
      Date_of_Birth: '1995-08-14',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Public Speaking, Traveling, Manipulating',
    },
    {
      Character_ID: 9,
      Project_ID: 901,
      Name: 'Daniel Blue',
      Age: 38,
      Role: 'Protagonist',
      First_Chapter_Appearance: 21,
      Description:
        'A skilled tactician and a natural leader with a strong moral compass.',
      Image: '',
      Date_of_Birth: '1986-04-30',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Strategizing, Reading, Playing the Violin',
    },
    {
      Character_ID: 10,
      Project_ID: 901,
      Name: 'Hannah Grey',
      Age: 26,
      Role: 'Supporting',
      First_Chapter_Appearance: 22,
      Description:
        'A tech genius with a talent for hacking and a rebellious streak.',
      Image: '',
      Date_of_Birth: '1998-11-15',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Coding, Gaming, Biking',
    },
    {
      Character_ID: 11,
      Project_ID: 1,
      Name: 'Nathan Reed',
      Age: 31,
      Role: 'Supporting',
      First_Chapter_Appearance: 4,
      Description:
        'An expert marksman and loyal ally, always ready to support the team.',
      Image: '',
      Date_of_Birth: '1993-02-11',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Target Shooting, Collecting Antiques, Reading',
    },
    {
      Character_ID: 12,
      Project_ID: 2,
      Name: 'Olivia Turner',
      Age: 27,
      Role: 'Antagonist',
      First_Chapter_Appearance: 6,
      Description:
        'A brilliant but ruthless corporate leader with a hidden agenda.',
      Image: '',
      Date_of_Birth: '1997-05-28',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Business Strategy, Wine Tasting, Traveling',
    },
    {
      Character_ID: 13,
      Project_ID: 5,
      Name: 'Ethan Brooks',
      Age: 34,
      Role: 'Supporting',
      First_Chapter_Appearance: 10,
      Description:
        'A tech-savvy engineer with a quick wit and resourceful nature.',
      Image: '',
      Date_of_Birth: '1990-07-20',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Robotics, DIY Projects, Video Games',
    },
    {
      Character_ID: 14,
      Project_ID: 6,
      Name: 'Isabella Ross',
      Age: 29,
      Role: 'Protagonist',
      First_Chapter_Appearance: 14,
      Description: 'A determined journalist uncovering the truth at any cost.',
      Image: '',
      Date_of_Birth: '1995-10-10',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Investigative Journalism, Reading, Yoga',
    },
    {
      Character_ID: 15,
      Project_ID: 899,
      Name: 'Liam Scott',
      Age: 32,
      Role: 'Antagonist',
      First_Chapter_Appearance: 18,
      Description: 'A former soldier turned mercenary with a complex past.',
      Image: '',
      Date_of_Birth: '1992-12-01',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Tactics, Shooting Sports, Running',
    },
    {
      Character_ID: 16,
      Project_ID: 901,
      Name: 'Sophia Carter',
      Age: 30,
      Role: 'Supporting',
      First_Chapter_Appearance: 23,
      Description: 'A skilled medic with a calm demeanor and a caring heart.',
      Image: '',
      Date_of_Birth: '1994-03-05',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Medicine, Reading, Volunteering',
    },
    {
      Character_ID: 17,
      Project_ID: 1,
      Name: 'Ryan Taylor',
      Age: 36,
      Role: 'Supporting',
      First_Chapter_Appearance: 4,
      Description:
        'A seasoned detective with a knack for solving complex cases.',
      Image: '',
      Date_of_Birth: '1988-09-13',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Detective Novels, Chess, Jogging',
    },
    {
      Character_ID: 18,
      Project_ID: 2,
      Name: 'Grace Martinez',
      Age: 28,
      Role: 'Protagonist',
      First_Chapter_Appearance: 6,
      Description:
        'A brilliant scientist dedicated to discovering new frontiers.',
      Image: '',
      Date_of_Birth: '1996-04-17',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Science, Experimenting, Reading',
    },
    {
      Character_ID: 19,
      Project_ID: 5,
      Name: 'Daniel Miller',
      Age: 33,
      Role: 'Antagonist',
      First_Chapter_Appearance: 9,
      Description:
        'A corrupt politician with a secretive and manipulative nature.',
      Image: '',
      Date_of_Birth: '1991-08-24',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Politics, Power Games, Investing',
    },
    {
      Character_ID: 20,
      Project_ID: 6,
      Name: 'Chloe Wilson',
      Age: 24,
      Role: 'Supporting',
      First_Chapter_Appearance: 14,
      Description:
        'A young hacker with exceptional skills and a rebellious attitude.',
      Image: '',
      Date_of_Birth: '2000-06-12',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Hacking, Gaming, Biking',
    },
    {
      Character_ID: 21,
      Project_ID: 899,
      Name: 'Matthew Perez',
      Age: 37,
      Role: 'Protagonist',
      First_Chapter_Appearance: 17,
      Description: 'A fearless leader fighting for freedom and justice.',
      Image: '',
      Date_of_Birth: '1987-11-21',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Leadership, Reading, Strategy Games',
    },
    {
      Character_ID: 22,
      Project_ID: 901,
      Name: 'Amelia Gonzalez',
      Age: 29,
      Role: 'Supporting',
      First_Chapter_Appearance: 22,
      Description: 'A compassionate nurse dedicated to helping others.',
      Image: '',
      Date_of_Birth: '1995-07-16',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Nursing, Volunteering, Gardening',
    },
    {
      Character_ID: 23,
      Project_ID: 1,
      Name: 'Lucas White',
      Age: 35,
      Role: 'Antagonist',
      First_Chapter_Appearance: 3,
      Description:
        'A cunning and manipulative businessman with a hidden agenda.',
      Image: '',
      Date_of_Birth: '1989-10-02',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Business Strategy, Poker, Traveling',
    },
    {
      Character_ID: 24,
      Project_ID: 2,
      Name: 'Victoria King',
      Age: 31,
      Role: 'Protagonist',
      First_Chapter_Appearance: 6,
      Description:
        'A determined and resourceful detective solving complex cases.',
      Image: '',
      Date_of_Birth: '1993-12-19',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Detective Novels, Puzzle Solving, Running',
    },
    {
      Character_ID: 25,
      Project_ID: 5,
      Name: 'Oliver Martin',
      Age: 34,
      Role: 'Supporting',
      First_Chapter_Appearance: 10,
      Description:
        'A talented artist with a mysterious and enigmatic personality.',
      Image: '',
      Date_of_Birth: '1990-05-08',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Painting, Sculpting, Reading',
    },
    {
      Character_ID: 26,
      Project_ID: 6,
      Name: 'Sophia Anderson',
      Age: 27,
      Role: 'Protagonist',
      First_Chapter_Appearance: 13,
      Description:
        'A brave and skilled fighter with a strong sense of justice.',
      Image: '',
      Date_of_Birth: '1997-01-30',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Martial Arts, Hiking, Cooking',
    },
  ],
  relationships: [
    {
      Relationship_ID: 1,
      Project_ID: 1,
      Character_ID_1: 1,
      Character_ID_2: 3,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 2,
      Project_ID: 2,
      Character_ID_1: 2,
      Character_ID_2: 4,
      Relationship_Type: 'Enemy',
    },
    {
      Relationship_ID: 3,
      Project_ID: 1,
      Character_ID_1: 3,
      Character_ID_2: 5,
      Relationship_Type: 'Family',
    },
    {
      Relationship_ID: 4,
      Project_ID: 1,
      Character_ID_1: 6,
      Character_ID_2: 7,
      Relationship_Type: 'Best Friend',
    },
    {
      Relationship_ID: 5,
      Project_ID: 1,
      Character_ID_1: 1,
      Character_ID_2: 11,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 6,
      Project_ID: 1,
      Character_ID_1: 11,
      Character_ID_2: 17,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 7,
      Project_ID: 2,
      Character_ID_1: 2,
      Character_ID_2: 12,
      Relationship_Type: 'Rival',
    },
    {
      Relationship_ID: 8,
      Project_ID: 1,
      Character_ID_1: 4,
      Character_ID_2: 18,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 9,
      Project_ID: 2,
      Character_ID_1: 6,
      Character_ID_2: 25,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 10,
      Project_ID: 6,
      Character_ID_1: 7,
      Character_ID_2: 14,
      Relationship_Type: 'Mentor',
    },
    {
      Relationship_ID: 11,
      Project_ID: 899,
      Character_ID_1: 8,
      Character_ID_2: 15,
      Relationship_Type: 'Business Partner',
    },
    {
      Relationship_ID: 12,
      Project_ID: 901,
      Character_ID_1: 9,
      Character_ID_2: 21,
      Relationship_Type: 'Ally',
    },
    {
      Relationship_ID: 13,
      Project_ID: 901,
      Character_ID_1: 10,
      Character_ID_2: 20,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 14,
      Project_ID: 2,
      Character_ID_1: 12,
      Character_ID_2: 23,
      Relationship_Type: 'Business Associate',
    },
    {
      Relationship_ID: 15,
      Project_ID: 6,
      Character_ID_1: 14,
      Character_ID_2: 26,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 16,
      Project_ID: 901,
      Character_ID_1: 16,
      Character_ID_2: 22,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 17,
      Project_ID: 1,
      Character_ID_1: 18,
      Character_ID_2: 24,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 18,
      Project_ID: 5,
      Character_ID_1: 19,
      Character_ID_2: 15,
      Relationship_Type: 'Enemy',
    },
    {
      Relationship_ID: 19,
      Project_ID: 2,
      Character_ID_1: 20,
      Character_ID_2: 10,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 20,
      Project_ID: 901,
      Character_ID_1: 21,
      Character_ID_2: 9,
      Relationship_Type: 'Comrade',
    },
    {
      Relationship_ID: 21,
      Project_ID: 1,
      Character_ID_1: 22,
      Character_ID_2: 16,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 22,
      Project_ID: 2,
      Character_ID_1: 23,
      Character_ID_2: 8,
      Relationship_Type: 'Rival',
    },
    {
      Relationship_ID: 23,
      Project_ID: 1,
      Character_ID_1: 24,
      Character_ID_2: 2,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 24,
      Project_ID: 899,
      Character_ID_1: 25,
      Character_ID_2: 19,
      Relationship_Type: 'Enemy',
    },
    {
      Relationship_ID: 25,
      Project_ID: 6,
      Character_ID_1: 26,
      Character_ID_2: 7,
      Relationship_Type: 'Mentor',
    },
  ],
  locations: [
    {
      Location_ID: 1,
      Name: 'Silverwood',
      Population: 15000,
      Image: '',
      Description:
        'A bustling town known for its lush forests and vibrant community.',
      Coordinates: '40.712776, -74.005974',
      Related_Locations: [2, 3],
      Project_ID: 1,
    },
    {
      Location_ID: 2,
      Name: "Drake's Bay",
      Population: 8500,
      Image: '',
      Description:
        'A coastal village famed for its beautiful beaches and historic lighthouse.',
      Coordinates: '36.778259, -119.417931',
      Related_Locations: [1, 4],
      Project_ID: 2,
    },
    {
      Location_ID: 3,
      Name: "Eagle's Peak",
      Population: 5000,
      Image: '',
      Description:
        'A small mountain town popular among hikers and nature enthusiasts.',
      Coordinates: '34.052235, -118.243683',
      Related_Locations: [1, 5],
      Project_ID: 5,
    },
    {
      Location_ID: 4,
      Name: 'Verdant Plains',
      Population: 2500,
      Image: '',
      Description:
        'A quiet rural area with vast farmlands and scenic landscapes.',
      Coordinates: '37.774929, -122.419418',
      Related_Locations: [2, 6],
      Project_ID: 6,
    },
    {
      Location_ID: 5,
      Name: 'Crimson City',
      Population: 200000,
      Image: '',
      Description:
        'A large metropolitan area known for its vibrant nightlife and cultural landmarks.',
      Coordinates: '34.052235, -118.243683',
      Related_Locations: [3, 7],
      Project_ID: 899,
    },
    {
      Location_ID: 6,
      Name: 'Azure Lake',
      Population: 1200,
      Image: '',
      Description:
        'A serene lakeside village renowned for its clear waters and peaceful environment.',
      Coordinates: '47.606209, -122.332069',
      Related_Locations: [4, 8],
      Project_ID: 901,
    },
    {
      Location_ID: 7,
      Name: 'Golden Sands',
      Population: 4500,
      Image: '',
      Description:
        'A popular desert town known for its unique rock formations and warm climate.',
      Coordinates: '36.169941, -115.139832',
      Related_Locations: [5, 9],
      Project_ID: 1,
    },
    {
      Location_ID: 8,
      Name: 'Maple Ridge',
      Population: 6700,
      Image: '',
      Description:
        'A picturesque town famous for its autumn foliage and cozy cottages.',
      Coordinates: '43.653225, -79.383186',
      Related_Locations: [6, 10],
      Project_ID: 2,
    },
    {
      Location_ID: 9,
      Name: 'Frostholm',
      Population: 2300,
      Image: '',
      Description:
        'A remote town in the snowy mountains, known for its winter sports and festivals.',
      Coordinates: '45.421530, -75.697193',
      Related_Locations: [7, 11],
      Project_ID: 5,
    },
    {
      Location_ID: 10,
      Name: 'Ivory Coast',
      Population: 9800,
      Image: '',
      Description:
        'A coastal city known for its luxurious resorts and pristine beaches.',
      Coordinates: '25.761681, -80.191788',
      Related_Locations: [8, 12],
      Project_ID: 6,
    },
    {
      Location_ID: 11,
      Name: 'Shadowmere',
      Population: 3400,
      Image: '',
      Description: 'A mysterious town with a rich history and many legends.',
      Coordinates: '51.509865, -0.118092',
      Related_Locations: [9, 13],
      Project_ID: 899,
    },
    {
      Location_ID: 12,
      Name: 'Sunset Valley',
      Population: 5600,
      Image: '',
      Description:
        'A valley known for its breathtaking sunsets and fertile lands.',
      Coordinates: '48.856613, 2.352222',
      Related_Locations: [10, 14],
      Project_ID: 901,
    },
    {
      Location_ID: 13,
      Name: 'Crystal Cove',
      Population: 7200,
      Image: '',
      Description:
        'A coastal town famous for its crystal clear waters and marine life.',
      Coordinates: '40.712776, -74.005974',
      Related_Locations: [11, 15],
      Project_ID: 1,
    },
    {
      Location_ID: 14,
      Name: 'Mossy Hollow',
      Population: 3200,
      Image: '',
      Description:
        'A hidden village surrounded by dense forests and ancient trees.',
      Coordinates: '35.689487, 139.691711',
      Related_Locations: [12, 16],
      Project_ID: 2,
    },
    {
      Location_ID: 15,
      Name: 'Copperfield',
      Population: 14000,
      Image: '',
      Description:
        'A historic town known for its mining heritage and old architecture.',
      Coordinates: '55.755825, 37.617298',
      Related_Locations: [13, 17],
      Project_ID: 5,
    },
    {
      Location_ID: 16,
      Name: 'New Harbor',
      Population: 11000,
      Image: '',
      Description:
        'A thriving port city with a bustling marketplace and rich cultural diversity.',
      Coordinates: '34.052235, -118.243683',
      Related_Locations: [14, 18],
      Project_ID: 6,
    },
    {
      Location_ID: 17,
      Name: 'Glimmerbrook',
      Population: 5300,
      Image: '',
      Description:
        'A magical town surrounded by enchanting forests and sparkling rivers.',
      Coordinates: '37.774929, -122.419418',
      Related_Locations: [15, 19],
      Project_ID: 899,
    },
    {
      Location_ID: 18,
      Name: 'Starlight City',
      Population: 90000,
      Image: '',
      Description:
        'A futuristic city known for its advanced technology and high skyscrapers.',
      Coordinates: '34.052235, -118.243683',
      Related_Locations: [16, 20],
      Project_ID: 901,
    },
    {
      Location_ID: 19,
      Name: 'Meadowfield',
      Population: 7600,
      Image: '',
      Description:
        'A charming town known for its flower fields and community festivals.',
      Coordinates: '51.507351, -0.127758',
      Related_Locations: [17, 21],
      Project_ID: 1,
    },
    {
      Location_ID: 20,
      Name: 'Ironforge',
      Population: 46000,
      Image: '',
      Description:
        'A city with a rich industrial history, known for its metalwork and factories.',
      Coordinates: '40.712776, -74.005974',
      Related_Locations: [18, 22],
      Project_ID: 2,
    },
    {
      Location_ID: 21,
      Name: 'Whispering Pines',
      Population: 4200,
      Image: '',
      Description:
        'A secluded village surrounded by towering pine trees and serene lakes.',
      Coordinates: '43.651070, -79.347015',
      Related_Locations: [19, 23],
      Project_ID: 5,
    },
    {
      Location_ID: 22,
      Name: 'Granite Falls',
      Population: 8700,
      Image: '',
      Description:
        'A town set in the mountains, famous for its granite quarries and scenic views.',
      Coordinates: '34.052235, -118.243683',
      Related_Locations: [20, 24],
      Project_ID: 6,
    },
    {
      Location_ID: 23,
      Name: 'Ravenwood',
      Population: 3300,
      Image: '',
      Description:
        'A dark and mysterious town with a rich folklore and eerie atmosphere.',
      Coordinates: '40.712776, -74.005974',
      Related_Locations: [21, 25],
      Project_ID: 899,
    },
    {
      Location_ID: 24,
      Name: 'Lakeside',
      Population: 2900,
      Image: '',
      Description:
        'A peaceful town situated by a large lake, known for its fishing and boating.',
      Coordinates: '37.774929, -122.419418',
      Related_Locations: [22, 26],
      Project_ID: 901,
    },
    {
      Location_ID: 25,
      Name: 'Thornfield',
      Population: 8000,
      Image: '',
      Description:
        'A quaint town with historic buildings and a vibrant arts scene.',
      Coordinates: '40.730610, -73.935242',
      Related_Locations: [23, 27],
      Project_ID: 1,
    },
    {
      Location_ID: 26,
      Name: 'Riverbend',
      Population: 3800,
      Image: '',
      Description:
        'A riverside town known for its beautiful riverwalk and community events.',
      Coordinates: '34.052235, -118.243683',
      Related_Locations: [24, 28],
      Project_ID: 2,
    },
    {
      Location_ID: 27,
      Name: 'Bluewater Bay',
      Population: 9100,
      Image: '',
      Description:
        'A coastal town with stunning ocean views and a thriving seafood industry.',
      Coordinates: '36.778259, -119.417931',
      Related_Locations: [25, 29],
      Project_ID: 5,
    },
    {
      Location_ID: 28,
      Name: 'Redwood',
      Population: 7600,
      Image: '',
      Description:
        'A town surrounded by towering redwoods, known for its timber industry.',
      Coordinates: '37.774929, -122.419418',
      Related_Locations: [26, 30],
      Project_ID: 6,
    },
    {
      Location_ID: 29,
      Name: 'Evergreen',
      Population: 6700,
      Image: '',
      Description:
        'A town with lush greenery and a focus on sustainability and eco-friendliness.',
      Coordinates: '40.712776, -74.005974',
      Related_Locations: [27, 31],
      Project_ID: 899,
    },
    {
      Location_ID: 30,
      Name: 'Sunrise Hills',
      Population: 3400,
      Image: '',
      Description:
        'A hilltop town known for its stunning sunrises and rolling hills.',
      Coordinates: '34.052235, -118.243683',
      Related_Locations: [28, 32],
      Project_ID: 901,
    },
  ],
  ideas: [
    {
      Idea_ID: 1,
      Title: 'Mystery of the Silverwood',
      Content:
        'A detective uncovers a series of strange events happening in the town of Silverwood.',
      Status: 'Not Used',
      Characters: [1, 2],
      Location: 1,
      Project_ID: 1,
    },
    {
      Idea_ID: 2,
      Title: "The Secret of Drake's Bay",
      Content:
        "A hidden treasure map is discovered, leading to an adventurous quest in Drake's Bay.",
      Status: 'Used',
      Characters: [3, 4],
      Location: 2,
      Project_ID: 2,
    },
    {
      Idea_ID: 3,
      Title: "Echoes of Eagle's Peak",
      Content:
        "A group of friends encounters mysterious echoes while hiking in Eagle's Peak.",
      Status: 'Not Used',
      Characters: [5, 6],
      Location: 3,
      Project_ID: 5,
    },
    {
      Idea_ID: 4,
      Title: 'Verdant Plains Chronicles',
      Content:
        'Life in the tranquil Verdant Plains takes a turn with the arrival of an enigmatic stranger.',
      Status: 'Used',
      Characters: [7, 8],
      Location: 4,
      Project_ID: 6,
    },
    {
      Idea_ID: 5,
      Title: 'Nightfall in Crimson City',
      Content:
        'A journalist investigates a series of crimes in the bustling Crimson City.',
      Status: 'Not Used',
      Characters: [9, 10],
      Location: 5,
      Project_ID: 899,
    },
    {
      Idea_ID: 6,
      Title: 'Mysteries of Azure Lake',
      Content:
        'A scientist discovers strange phenomena occurring in the peaceful Azure Lake.',
      Status: 'Used',
      Characters: [11, 12],
      Location: 6,
      Project_ID: 901,
    },
    {
      Idea_ID: 7,
      Title: 'Legends of Golden Sands',
      Content:
        'Explorers search for ancient artifacts buried in the desert town of Golden Sands.',
      Status: 'Not Used',
      Characters: [13, 14],
      Location: 7,
      Project_ID: 1,
    },
    {
      Idea_ID: 8,
      Title: 'Whispers in Maple Ridge',
      Content:
        'A writer moves to Maple Ridge and begins hearing whispers that lead to a hidden secret.',
      Status: 'Used',
      Characters: [15, 16],
      Location: 8,
      Project_ID: 2,
    },
    {
      Idea_ID: 9,
      Title: 'Frostholm Tales',
      Content:
        'Residents of Frostholm share chilling tales of the supernatural during a winter storm.',
      Status: 'Not Used',
      Characters: [17, 18],
      Location: 9,
      Project_ID: 5,
    },
    {
      Idea_ID: 10,
      Title: 'Ivory Coast Mysteries',
      Content:
        'A group of tourists uncovers a hidden conspiracy in the luxurious Ivory Coast.',
      Status: 'Used',
      Characters: [19, 20],
      Location: 10,
      Project_ID: 6,
    },
    {
      Idea_ID: 11,
      Title: 'The Enigma of Shadowmere',
      Content:
        'An ancient artifact is discovered in Shadowmere, leading to a series of mysterious events.',
      Status: 'Not Used',
      Characters: null,
      Location: 11,
      Project_ID: 899,
    },
    {
      Idea_ID: 12,
      Title: 'Sunset Valley Serenade',
      Content:
        'A romance blossoms in the picturesque Sunset Valley amidst the backdrop of stunning sunsets.',
      Status: 'Used',
      Characters: [21, 22],
      Location: null,
      Project_ID: 901,
    },
    {
      Idea_ID: 13,
      Title: 'Crystal Cove Adventures',
      Content:
        'Young explorers embark on an adventure to uncover the secrets of Crystal Cove.',
      Status: 'Not Used',
      Characters: null,
      Location: 13,
      Project_ID: 1,
    },
    {
      Idea_ID: 14,
      Title: 'Tales from Mossy Hollow',
      Content:
        'Residents of Mossy Hollow share stories of the ancient forest and its magical properties.',
      Status: 'Used',
      Characters: null,
      Location: 14,
      Project_ID: 2,
    },
    {
      Idea_ID: 15,
      Title: 'Copperfield Chronicles',
      Content:
        'The history of Copperfield is revealed through a series of interconnected stories.',
      Status: 'Not Used',
      Characters: [23, 24],
      Location: 15,
      Project_ID: 5,
    },
    {
      Idea_ID: 16,
      Title: 'New Harbor Nights',
      Content:
        'A detective unravels a web of intrigue and deception in the bustling port city of New Harbor.',
      Status: 'Used',
      Characters: [25, 26],
      Location: 16,
      Project_ID: 6,
    },
    {
      Idea_ID: 17,
      Title: 'Glimmerbrook Legends',
      Content:
        'Glimmerbrook is filled with magical tales and enchanting adventures.',
      Status: 'Not Used',
      Characters: null,
      Location: 17,
      Project_ID: 899,
    },
    {
      Idea_ID: 18,
      Title: 'Starlight City Stories',
      Content:
        'In the futuristic Starlight City, technology and humanity collide in unexpected ways.',
      Status: 'Used',
      Characters: null,
      Location: 18,
      Project_ID: 901,
    },
    {
      Idea_ID: 19,
      Title: 'Meadowfield Mysteries',
      Content:
        'Strange occurrences in the charming town of Meadowfield lead to a deeper investigation.',
      Status: 'Not Used',
      Characters: [27, 28],
      Location: 19,
      Project_ID: 1,
    },
    {
      Idea_ID: 20,
      Title: 'Ironforge Saga',
      Content:
        'The industrial history of Ironforge is brought to life through the stories of its people.',
      Status: 'Used',
      Characters: null,
      Location: 20,
      Project_ID: 2,
    },
    {
      Idea_ID: 21,
      Title: 'Whispering Pines Secrets',
      Content:
        'A secluded village hides dark secrets that are slowly uncovered by a newcomer.',
      Status: 'Not Used',
      Characters: [29, 30],
      Location: 21,
      Project_ID: 5,
    },
    {
      Idea_ID: 22,
      Title: 'Granite Falls Adventures',
      Content:
        'Outdoor enthusiasts explore the rugged terrain and hidden secrets of Granite Falls.',
      Status: 'Used',
      Characters: null,
      Location: 22,
      Project_ID: 6,
    },
    {
      Idea_ID: 23,
      Title: 'Ravenwood Tales',
      Content:
        'The dark and mysterious town of Ravenwood is filled with legends and lore.',
      Status: 'Not Used',
      Characters: null,
      Location: 23,
      Project_ID: 899,
    },
    {
      Idea_ID: 24,
      Title: 'Pinehurst Stories',
      Content:
        'A series of short stories set in the cozy town of Pinehurst, known for its local traditions.',
      Status: 'Used',
      Characters: [31, 32],
      Location: 24,
      Project_ID: 901,
    },
    {
      Idea_ID: 25,
      Title: 'Lakeside Whispers',
      Content:
        'Mysterious events at a lakeside village lead to a thrilling investigation.',
      Status: 'Not Used',
      Characters: null,
      Location: 25,
      Project_ID: 1,
    },
    {
      Idea_ID: 26,
      Title: 'Stonebridge Legends',
      Content:
        'The medieval architecture and rich history of Stonebridge come alive through its tales.',
      Status: 'Used',
      Characters: [33, 34],
      Location: 26,
      Project_ID: 2,
    },
    {
      Idea_ID: 27,
      Title: 'Blossom Hill Mysteries',
      Content:
        'The blooming flowers and stunning views of Blossom Hill hide dark secrets.',
      Status: 'Not Used',
      Characters: null,
      Location: 27,
      Project_ID: 5,
    },
    {
      Idea_ID: 28,
      Title: 'Sunrise Valley Chronicles',
      Content:
        'A valley known for its beautiful sunrises holds stories of hope and resilience.',
      Status: 'Used',
      Characters: [35, 36],
      Location: 28,
      Project_ID: 6,
    },
    {
      Idea_ID: 29,
      Title: 'Thornfield Enigma',
      Content:
        'The unique flora of Thornfield leads to unexpected discoveries.',
      Status: 'Not Used',
      Characters: null,
      Location: 29,
      Project_ID: 899,
    },
    {
      Idea_ID: 30,
      Title: 'Breezeway Adventures',
      Content:
        'The strong winds and windsurfing spots of Breezeway are the backdrop for exciting tales.',
      Status: 'Used',
      Characters: null,
      Location: 30,
      Project_ID: 901,
    },
  ],
};

export default projectData;
