export const projectData = {
  projects: [
    {
      Project_ID: 1,
      Name: 'Project A',
      Created_by: 1,
    },
    {
      Project_ID: 2,
      Name: 'Project B',
      Created_by: 1,
    },
    {
      Project_ID: 5,
      Name: 'Project E',
      Created_by: 1,
    },
    {
      Project_ID: 6,
      Name: 'Project F',
      Created_by: 1,
    },
    {
      Project_ID: 899,
      Name: 'Project CD',
      Created_by: 2,
    },
    {
      Project_ID: 901,
      Name: 'Project Deez',
      Created_by: 2,
    },
  ],
  chapters: [
    {
      Chapter_ID: 1,
      Project_ID: 1,
      Chapter_Number: 1,
      Chapter_Name: 'The Beginning',
      Chapter_Content: [
        {
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'CENTRAL PARK - BENCH',
          time: 'DAY',
        },
        {
          type: 'action',
          content: 'John runs across the park, dodging people as he goes.',
        },
        {
          type: 'dialogue',
          character: 'JOHN',
          extension: 'V.O.',
          parenthetical: '(whispering)',
          dialogue: "I must find the package before it's too late.",
        },
        {
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'CITY STREET - NIGHT',
          time: 'NIGHT',
        },
        {
          type: 'action',
          content:
            'A car screeches to a halt in front of the building. The driver leans out, scanning the street.',
        },
        {
          type: 'dialogue',
          character: 'SARA',
          extension: 'O.S.',
          parenthetical: '(shouting)',
          dialogue: 'Get in, now!',
        },
        {
          type: 'transition',
          transition: 'FADE OUT:',
        },
        {
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'ABANDONED WAREHOUSE',
          time: 'NIGHT',
        },
        {
          type: 'action',
          content:
            'The dimly lit warehouse is filled with old, rusted machinery. A single light bulb swings from the ceiling, casting eerie shadows.',
        },
        {
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(determined)',
          dialogue: 'We have to be quiet. They could be anywhere.',
        },
        {
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(nervous)',
          dialogue: "I don't like this, John. We should have brought backup.",
        },
        {
          type: 'action',
          content:
            'Suddenly, a loud crash echoes through the building. John and Sara freeze.',
        },
        {
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(whispering)',
          dialogue: 'Stay close to me.',
        },
        {
          type: 'transition',
          transition: 'SMASH CUT TO:',
        },
        {
          type: 'scene-headings',
          is_subheading: false,
          interior: 'EXT.',
          location: 'ROOFTOP - NIGHT',
          time: 'NIGHT',
        },
        {
          type: 'action',
          content:
            'The city skyline glows in the distance. John and Sara emerge from a stairwell, breathless.',
        },
        {
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(relieved)',
          dialogue: 'We made it. What now?',
        },
        {
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(resolute)',
          dialogue: 'Now we wait for the signal.',
        },
        {
          type: 'action',
          content:
            'In the distance, a red flare shoots up into the sky. John nods.',
        },
        {
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(focused)',
          dialogue: "There it is. Let's move.",
        },
        {
          type: 'transition',
          transition: 'DISSOLVE TO:',
        },
        {
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'SECRET LAB - NIGHT',
          time: 'NIGHT',
        },
        {
          type: 'action',
          content:
            'The lab is filled with high-tech equipment. John and Sara move stealthily, avoiding the security cameras.',
        },
        {
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(whispering)',
          dialogue: 'This place gives me the creeps.',
        },
        {
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(serious)',
          dialogue: "Stay focused. We're almost there.",
        },
        {
          type: 'action',
          content:
            'They reach a door marked "AUTHORIZED PERSONNEL ONLY." John pulls out a device and starts hacking the lock.',
        },
        {
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(anxious)',
          dialogue: "Hurry up, John. We don't have much time.",
        },
        {
          type: 'transition',
          transition: 'CUT TO:',
        },
        {
          type: 'scene-headings',
          is_subheading: false,
          interior: 'INT.',
          location: 'CONTROL ROOM - NIGHT',
          time: 'NIGHT',
        },
        {
          type: 'action',
          content:
            'The control room is filled with monitors showing various parts of the facility. John and Sara enter and quickly start downloading data from a terminal.',
        },
        {
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(focused)',
          dialogue: "Keep an eye on the door. I'm almost done here.",
        },
        {
          type: 'dialogue',
          character: 'SARA',
          extension: '',
          parenthetical: '(tense)',
          dialogue: "I don't like this. We need to get out of here.",
        },
        {
          type: 'action',
          content:
            'A loud alarm suddenly blares. Red lights flash as the room goes into lockdown.',
        },
        {
          type: 'dialogue',
          character: 'JOHN',
          extension: '',
          parenthetical: '(urgent)',
          dialogue: "Got it! Let's go!",
        },
        {
          type: 'transition',
          transition: 'FADE OUT:',
        },
      ],
    },
    {
      Chapter_ID: 2,
      Project_ID: 1,
      Chapter_Number: 2,
      Chapter_Name: 'A New Challenge',
      Chapter_Content:
        'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      Chapter_ID: 3,
      Project_ID: 1,
      Chapter_Number: 3,
      Chapter_Name: 'Secrets Unveiled',
      Chapter_Content:
        'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    },
    {
      Chapter_ID: 4,
      Project_ID: 1,
      Chapter_Number: 4,
      Chapter_Name: 'The Journey Begins',
      Chapter_Content:
        'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    },
    {
      Chapter_ID: 5,
      Project_ID: 2,
      Chapter_Number: 1,
      Chapter_Name: 'Crossroads',
      Chapter_Content:
        'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
      Chapter_ID: 6,
      Project_ID: 2,
      Chapter_Number: 2,
      Chapter_Name: 'Hidden Truths',
      Chapter_Content:
        'Curabitur pretium tincidunt lacus. Nulla gravida orci a odio.',
    },
    {
      Chapter_ID: 7,
      Project_ID: 2,
      Chapter_Number: 3,
      Chapter_Name: 'Rising Tensions',
      Chapter_Content:
        'Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris.',
    },
    {
      Chapter_ID: 8,
      Project_ID: 2,
      Chapter_Number: 4,
      Chapter_Name: 'A Twist of Fate',
      Chapter_Content: 'Integer in mauris eu nibh euismod gravida.',
    },
    {
      Chapter_ID: 9,
      Project_ID: 5,
      Chapter_Number: 1,
      Chapter_Name: 'Battle Lines',
      Chapter_Content: 'Vivamus commodo. Nulla sed leo.',
    },
    {
      Chapter_ID: 10,
      Project_ID: 5,
      Chapter_Number: 2,
      Chapter_Name: 'Unexpected Allies',
      Chapter_Content:
        'Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.',
    },
    {
      Chapter_ID: 11,
      Project_ID: 5,
      Chapter_Number: 3,
      Chapter_Name: 'The Darkest Hour',
      Chapter_Content: 'Maecenas fermentum consequat mi.',
    },
    {
      Chapter_ID: 12,
      Project_ID: 5,
      Chapter_Number: 4,
      Chapter_Name: 'Revelation',
      Chapter_Content: 'Donec fermentum. Pellentesque malesuada nulla a mi.',
    },
    {
      Chapter_ID: 13,
      Project_ID: 6,
      Chapter_Number: 1,
      Chapter_Name: 'The Turning Point',
      Chapter_Content:
        'Suspendisse eu ligula. Donec bibendum. Pellentesque posuere.',
    },
    {
      Chapter_ID: 14,
      Project_ID: 6,
      Chapter_Number: 2,
      Chapter_Name: 'Shadows of the Past',
      Chapter_Content: 'Quisque ullamcorper placerat ipsum. Cras nibh.',
    },
    {
      Chapter_ID: 15,
      Project_ID: 6,
      Chapter_Number: 3,
      Chapter_Name: 'The Great Escape',
      Chapter_Content:
        'Morbi vel justo vitae lacus tincidunt ultrices. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
    },
    {
      Chapter_ID: 16,
      Project_ID: 6,
      Chapter_Number: 4,
      Chapter_Name: 'Unlikely Heroes',
      Chapter_Content: 'Vestibulum sed ante. Donec sagittis euismod purus.',
    },
    {
      Chapter_ID: 17,
      Project_ID: 899,
      Chapter_Number: 1,
      Chapter_Name: 'Conspiracy Uncovered',
      Chapter_Content:
        'Curabitur pretium tincidunt lacus. Nulla gravida orci a odio.',
    },
    {
      Chapter_ID: 18,
      Project_ID: 899,
      Chapter_Number: 2,
      Chapter_Name: 'The Final Countdown',
      Chapter_Content:
        'Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris.',
    },
    {
      Chapter_ID: 19,
      Project_ID: 899,
      Chapter_Number: 3,
      Chapter_Name: 'A Glimmer of Hope',
      Chapter_Content: 'Vivamus commodo. Nulla sed leo.',
    },
    {
      Chapter_ID: 20,
      Project_ID: 899,
      Chapter_Number: 4,
      Chapter_Name: 'The Ultimate Sacrifice',
      Chapter_Content:
        'Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.',
    },
    {
      Chapter_ID: 21,
      Project_ID: 901,
      Chapter_Number: 1,
      Chapter_Name: 'Redemption',
      Chapter_Content:
        'Curabitur pretium tincidunt lacus. Nulla gravida orci a odio.',
    },
    {
      Chapter_ID: 22,
      Project_ID: 901,
      Chapter_Number: 2,
      Chapter_Name: 'The Last Stand',
      Chapter_Content:
        'Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris.',
    },
    {
      Chapter_ID: 23,
      Project_ID: 901,
      Chapter_Number: 3,
      Chapter_Name: 'Aftermath',
      Chapter_Content: 'Vivamus commodo. Nulla sed leo.',
    },
    {
      Chapter_ID: 24,
      Project_ID: 901,
      Chapter_Number: 4,
      Chapter_Name: 'New Beginnings',
      Chapter_Content:
        'Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat.',
    },
  ],
  characters: [
    {
      Character_ID: 1,
      Project_ID: 1,
      Name: 'John Doe',
      Age: 30,
      Role: 'Protagonist',
      First_Chapter_Appearance: 1,
      Description: 'A brave and determined leader who fights for justice.',
      Image: '',
      Date_of_Birth: '1994-01-15',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Reading, Hiking, Strategy Games',
    },
    {
      Character_ID: 2,
      Project_ID: 2,
      Name: 'Jane Smith',
      Age: 25,
      Role: 'Antagonist',
      First_Chapter_Appearance: 5,
      Description: 'A cunning and ambitious individual with a mysterious past.',
      Image: '',
      Date_of_Birth: '1999-06-22',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Chess, Painting, Fencing',
    },
    {
      Character_ID: 3,
      Project_ID: 1,
      Name: 'Alex Johnson',
      Age: 35,
      Role: 'Supporting',
      First_Chapter_Appearance: 2,
      Description:
        'A loyal friend and skilled warrior with a troubled history.',
      Image: '',
      Date_of_Birth: '1989-11-05',
      Date_of_Death: '',
      Gender: 'Non-binary',
      Interests_Hobbies: 'Martial Arts, Cooking, Gardening',
    },
    {
      Character_ID: 4,
      Project_ID: 1,
      Name: 'Emily Davis',
      Age: 28,
      Role: 'Supporting',
      First_Chapter_Appearance: 3,
      Description: 'A brilliant scientist with a passion for discovery.',
      Image: '',
      Date_of_Birth: '1996-03-18',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Reading, Experimenting, Traveling',
    },
    {
      Character_ID: 5,
      Project_ID: 2,
      Name: 'Michael Brown',
      Age: 40,
      Role: 'Protagonist',
      First_Chapter_Appearance: 5,
      Description:
        'A seasoned detective with a sharp mind and a strong sense of justice.',
      Image: '',
      Date_of_Birth: '1984-07-11',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Puzzle Solving, Jogging, Fishing',
    },
    {
      Character_ID: 6,
      Project_ID: 5,
      Name: 'Samantha White',
      Age: 32,
      Role: 'Protagonist',
      First_Chapter_Appearance: 9,
      Description:
        'A fearless explorer with a knack for uncovering hidden secrets.',
      Image: '',
      Date_of_Birth: '1992-12-25',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Rock Climbing, Photography, Archaeology',
    },
    {
      Character_ID: 7,
      Project_ID: 6,
      Name: 'Robert Green',
      Age: 45,
      Role: 'Supporting',
      First_Chapter_Appearance: 13,
      Description: 'A wise mentor with years of experience and knowledge.',
      Image: '',
      Date_of_Birth: '1979-09-03',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Meditation, Teaching, Chess',
    },
    {
      Character_ID: 8,
      Project_ID: 899,
      Name: 'Laura Black',
      Age: 29,
      Role: 'Antagonist',
      First_Chapter_Appearance: 17,
      Description: 'A charismatic leader with a dark side and a hidden agenda.',
      Image: '',
      Date_of_Birth: '1995-08-14',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Public Speaking, Traveling, Manipulating',
    },
    {
      Character_ID: 9,
      Project_ID: 901,
      Name: 'Daniel Blue',
      Age: 38,
      Role: 'Protagonist',
      First_Chapter_Appearance: 21,
      Description:
        'A skilled tactician and a natural leader with a strong moral compass.',
      Image: '',
      Date_of_Birth: '1986-04-30',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Strategizing, Reading, Playing the Violin',
    },
    {
      Character_ID: 10,
      Project_ID: 901,
      Name: 'Hannah Grey',
      Age: 26,
      Role: 'Supporting',
      First_Chapter_Appearance: 22,
      Description:
        'A tech genius with a talent for hacking and a rebellious streak.',
      Image: '',
      Date_of_Birth: '1998-11-15',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Coding, Gaming, Biking',
    },
    {
      Character_ID: 11,
      Project_ID: 1,
      Name: 'Nathan Reed',
      Age: 31,
      Role: 'Supporting',
      First_Chapter_Appearance: 4,
      Description:
        'An expert marksman and loyal ally, always ready to support the team.',
      Image: '',
      Date_of_Birth: '1993-02-11',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Target Shooting, Collecting Antiques, Reading',
    },
    {
      Character_ID: 12,
      Project_ID: 2,
      Name: 'Olivia Turner',
      Age: 27,
      Role: 'Antagonist',
      First_Chapter_Appearance: 6,
      Description:
        'A brilliant but ruthless corporate leader with a hidden agenda.',
      Image: '',
      Date_of_Birth: '1997-05-28',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Business Strategy, Wine Tasting, Traveling',
    },
    {
      Character_ID: 13,
      Project_ID: 5,
      Name: 'Ethan Brooks',
      Age: 34,
      Role: 'Supporting',
      First_Chapter_Appearance: 10,
      Description:
        'A tech-savvy engineer with a quick wit and resourceful nature.',
      Image: '',
      Date_of_Birth: '1990-07-20',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Robotics, DIY Projects, Video Games',
    },
    {
      Character_ID: 14,
      Project_ID: 6,
      Name: 'Isabella Ross',
      Age: 29,
      Role: 'Protagonist',
      First_Chapter_Appearance: 14,
      Description: 'A determined journalist uncovering the truth at any cost.',
      Image: '',
      Date_of_Birth: '1995-10-10',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Investigative Journalism, Reading, Yoga',
    },
    {
      Character_ID: 15,
      Project_ID: 899,
      Name: 'Liam Scott',
      Age: 32,
      Role: 'Antagonist',
      First_Chapter_Appearance: 18,
      Description: 'A former soldier turned mercenary with a complex past.',
      Image: '',
      Date_of_Birth: '1992-12-01',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Tactics, Shooting Sports, Running',
    },
    {
      Character_ID: 16,
      Project_ID: 901,
      Name: 'Sophia Carter',
      Age: 30,
      Role: 'Supporting',
      First_Chapter_Appearance: 23,
      Description: 'A skilled medic with a calm demeanor and a caring heart.',
      Image: '',
      Date_of_Birth: '1994-03-05',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Medicine, Reading, Volunteering',
    },
    {
      Character_ID: 17,
      Project_ID: 1,
      Name: 'Ryan Taylor',
      Age: 36,
      Role: 'Supporting',
      First_Chapter_Appearance: 4,
      Description:
        'A seasoned detective with a knack for solving complex cases.',
      Image: '',
      Date_of_Birth: '1988-09-13',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Detective Novels, Chess, Jogging',
    },
    {
      Character_ID: 18,
      Project_ID: 2,
      Name: 'Grace Martinez',
      Age: 28,
      Role: 'Protagonist',
      First_Chapter_Appearance: 6,
      Description:
        'A brilliant scientist dedicated to discovering new frontiers.',
      Image: '',
      Date_of_Birth: '1996-04-17',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Science, Experimenting, Reading',
    },
    {
      Character_ID: 19,
      Project_ID: 5,
      Name: 'Daniel Miller',
      Age: 33,
      Role: 'Antagonist',
      First_Chapter_Appearance: 9,
      Description:
        'A corrupt politician with a secretive and manipulative nature.',
      Image: '',
      Date_of_Birth: '1991-08-24',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Politics, Power Games, Investing',
    },
    {
      Character_ID: 20,
      Project_ID: 6,
      Name: 'Chloe Wilson',
      Age: 24,
      Role: 'Supporting',
      First_Chapter_Appearance: 14,
      Description:
        'A young hacker with exceptional skills and a rebellious attitude.',
      Image: '',
      Date_of_Birth: '2000-06-12',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Hacking, Gaming, Biking',
    },
    {
      Character_ID: 21,
      Project_ID: 899,
      Name: 'Matthew Perez',
      Age: 37,
      Role: 'Protagonist',
      First_Chapter_Appearance: 17,
      Description: 'A fearless leader fighting for freedom and justice.',
      Image: '',
      Date_of_Birth: '1987-11-21',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Leadership, Reading, Strategy Games',
    },
    {
      Character_ID: 22,
      Project_ID: 901,
      Name: 'Amelia Gonzalez',
      Age: 29,
      Role: 'Supporting',
      First_Chapter_Appearance: 22,
      Description: 'A compassionate nurse dedicated to helping others.',
      Image: '',
      Date_of_Birth: '1995-07-16',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Nursing, Volunteering, Gardening',
    },
    {
      Character_ID: 23,
      Project_ID: 1,
      Name: 'Lucas White',
      Age: 35,
      Role: 'Antagonist',
      First_Chapter_Appearance: 3,
      Description:
        'A cunning and manipulative businessman with a hidden agenda.',
      Image: '',
      Date_of_Birth: '1989-10-02',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Business Strategy, Poker, Traveling',
    },
    {
      Character_ID: 24,
      Project_ID: 2,
      Name: 'Victoria King',
      Age: 31,
      Role: 'Protagonist',
      First_Chapter_Appearance: 6,
      Description:
        'A determined and resourceful detective solving complex cases.',
      Image: '',
      Date_of_Birth: '1993-12-19',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Detective Novels, Puzzle Solving, Running',
    },
    {
      Character_ID: 25,
      Project_ID: 5,
      Name: 'Oliver Martin',
      Age: 34,
      Role: 'Supporting',
      First_Chapter_Appearance: 10,
      Description:
        'A talented artist with a mysterious and enigmatic personality.',
      Image: '',
      Date_of_Birth: '1990-05-08',
      Date_of_Death: '',
      Gender: 'Male',
      Interests_Hobbies: 'Painting, Sculpting, Reading',
    },
    {
      Character_ID: 26,
      Project_ID: 6,
      Name: 'Sophia Anderson',
      Age: 27,
      Role: 'Protagonist',
      First_Chapter_Appearance: 13,
      Description:
        'A brave and skilled fighter with a strong sense of justice.',
      Image: '',
      Date_of_Birth: '1997-01-30',
      Date_of_Death: '',
      Gender: 'Female',
      Interests_Hobbies: 'Martial Arts, Hiking, Cooking',
    },
  ],
  relationships: [
    {
      Relationship_ID: 1,
      Project_ID: 1,
      Character_ID_1: 1,
      Character_ID_2: 3,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 2,
      Project_ID: 2,
      Character_ID_1: 2,
      Character_ID_2: 4,
      Relationship_Type: 'Enemy',
    },
    {
      Relationship_ID: 3,
      Project_ID: 1,
      Character_ID_1: 3,
      Character_ID_2: 5,
      Relationship_Type: 'Family',
    },
    {
      Relationship_ID: 4,
      Project_ID: 1,
      Character_ID_1: 6,
      Character_ID_2: 7,
      Relationship_Type: 'Best Friend',
    },
    {
      Relationship_ID: 5,
      Project_ID: 1,
      Character_ID_1: 1,
      Character_ID_2: 11,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 6,
      Project_ID: 1,
      Character_ID_1: 11,
      Character_ID_2: 17,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 7,
      Project_ID: 2,
      Character_ID_1: 2,
      Character_ID_2: 12,
      Relationship_Type: 'Rival',
    },
    {
      Relationship_ID: 8,
      Project_ID: 1,
      Character_ID_1: 4,
      Character_ID_2: 18,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 9,
      Project_ID: 2,
      Character_ID_1: 6,
      Character_ID_2: 25,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 10,
      Project_ID: 6,
      Character_ID_1: 7,
      Character_ID_2: 14,
      Relationship_Type: 'Mentor',
    },
    {
      Relationship_ID: 11,
      Project_ID: 899,
      Character_ID_1: 8,
      Character_ID_2: 15,
      Relationship_Type: 'Business Partner',
    },
    {
      Relationship_ID: 12,
      Project_ID: 901,
      Character_ID_1: 9,
      Character_ID_2: 21,
      Relationship_Type: 'Ally',
    },
    {
      Relationship_ID: 13,
      Project_ID: 901,
      Character_ID_1: 10,
      Character_ID_2: 20,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 14,
      Project_ID: 2,
      Character_ID_1: 12,
      Character_ID_2: 23,
      Relationship_Type: 'Business Associate',
    },
    {
      Relationship_ID: 15,
      Project_ID: 6,
      Character_ID_1: 14,
      Character_ID_2: 26,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 16,
      Project_ID: 901,
      Character_ID_1: 16,
      Character_ID_2: 22,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 17,
      Project_ID: 1,
      Character_ID_1: 18,
      Character_ID_2: 24,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 18,
      Project_ID: 5,
      Character_ID_1: 19,
      Character_ID_2: 15,
      Relationship_Type: 'Enemy',
    },
    {
      Relationship_ID: 19,
      Project_ID: 2,
      Character_ID_1: 20,
      Character_ID_2: 10,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 20,
      Project_ID: 901,
      Character_ID_1: 21,
      Character_ID_2: 9,
      Relationship_Type: 'Comrade',
    },
    {
      Relationship_ID: 21,
      Project_ID: 1,
      Character_ID_1: 22,
      Character_ID_2: 16,
      Relationship_Type: 'Colleague',
    },
    {
      Relationship_ID: 22,
      Project_ID: 2,
      Character_ID_1: 23,
      Character_ID_2: 8,
      Relationship_Type: 'Rival',
    },
    {
      Relationship_ID: 23,
      Project_ID: 1,
      Character_ID_1: 24,
      Character_ID_2: 2,
      Relationship_Type: 'Friend',
    },
    {
      Relationship_ID: 24,
      Project_ID: 899,
      Character_ID_1: 25,
      Character_ID_2: 19,
      Relationship_Type: 'Enemy',
    },
    {
      Relationship_ID: 25,
      Project_ID: 6,
      Character_ID_1: 26,
      Character_ID_2: 7,
      Relationship_Type: 'Mentor',
    },
  ],
};

export default projectData;
